### test login (disable csrf at security config to successfully login)
```
POST localhost:8080/login/auth
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### test register
POST localhost:8080/api/user/register
Content-Type: application/json

{
"username": "admin2",
"password": "123456"
}

